[package]
name = "imgproc-io"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
imgproc-core = { path = "../imgproc-core" }
image = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
